In [3]:
import pandas as pd

In [8]:
jan = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202501-divvy-tripdata.csv")
feb = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202502-divvy-tripdata.csv")
mar = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202503-divvy-tripdata.csv")
apr = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202504-divvy-tripdata.csv")
may = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202505-divvy-tripdata.csv")
jun = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202506-divvy-tripdata.csv")
jul = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202507-divvy-tripdata.csv")
aug = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202508-divvy-tripdata.csv")
sep = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202509-divvy-tripdata.csv")
octo = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202510-divvy-tripdata.csv")
nov = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202511-divvy-tripdata.csv")
dec = pd.read_csv(r"C:\Users\laksh\OneDrive\Desktop\CAPSTONE PROJECT DATA\RAW\202512-divvy-tripdata.csv")

In [18]:
cyclistic = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, octo, nov, dec], ignore_index = True)

In [21]:
cyclistic.shape

(5552994, 13)

In [22]:
cyclistic.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [24]:
cyclistic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 550.8+ MB

In [27]:
#check for number for null values in each column
cyclistic.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

In [29]:
#check if duplicated rows exist in the dataframe
cyclistic.duplicated().sum()

np.int64(0)

In [35]:
#convert started_at and ended_at columns to datetime format
cyclistic['started_at'] = pd.to_datetime(cyclistic['started_at'])
cyclistic['ended_at'] = pd.to_datetime(cyclistic['ended_at'])

#verify data types
cyclistic.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [43]:
#add ride_length column
cyclistic['ride_length'] = cyclistic['ended_at'] - cyclistic['started_at']

#convert ride_length values to minutes
cyclistic['ride_length'] = cyclistic['ride_length'].dt.total_seconds() / 60

In [45]:
#Rides less than 1 minute could be errors or test rides. So we remove them.
cyclistic = cyclistic[cyclistic['ride_length'] > 1]

In [47]:
#remove duplicate rides based on ride_id
cyclistic = cyclistic.drop_duplicates(subset = 'ride_id')

In [49]:
#check again for null values after removing duplicates
cyclistic.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1095320
start_station_id      1095320
end_station_name      1131808
end_station_id        1131808
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
ride_length                 0
dtype: int64

In [50]:
#remove rows with missing start or end station names.
cyclistic = cyclistic.dropna(subset = ['start_station_name','end_station_name'])

In [55]:
#CREATE NEW COLUMNS FOR ANALYSIS

In [60]:
#extract the day of the week from started_at column to analyze weekday vs weekend behavior
cyclistic['day_of_week'] = cyclistic['started_at'].dt.day_name()

#extract month name to monitor monthly trends
cyclistic['month'] = cyclistic['started_at'].dt.month_name()

#extract hour of the ride start time to identify peak riding hours during the day.
cyclistic['hour'] = cyclistic['started_at'].dt.hour

In [62]:
#preview cleaned dataset
cyclistic.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,month,hour
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member,13.957950,Tuesday,January,17
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member,5.072400,Saturday,January,15
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member,11.591667,Thursday,January,15
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,3.570550,Thursday,January,8
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member,2.573817,Thursday,January,8

In [63]:
#generate summary statistic for numerical columns
cyclistic.describe()

,started_at,ended_at,start_lat,start_lng,end_lat,end_lng,ride_length,hour
count,3661656,3661656,3.661656e+06,3.661656e+06,3.661656e+06,3.661656e+06,3.661656e+06,3.661656e+06
mean,2025-07-18 17:36:00.425335808,2025-07-18 17:52:03.799822592,4.190085e+01,-8.764480e+01,4.190144e+01,-8.764512e+01,1.605624e+01,1.391521e+01
min,2024-12-31 18:54:41.803000,2025-01-01 00:00:51.212000,4.164850e+01,-8.784411e+01,4.164850e+01,-8.784396e+01,1.000017e+00,0.000000e+00
25%,2025-05-23 17:41:30.955750144,2025-05-23 17:59:29.527500032,4.188103e+01,-8.765703e+01,4.188132e+01,-8.765842e+01,5.827567e+00,1.000000e+01
50%,2025-07-24 08:47:10.992000,2025-07-24 09:00:34.624000,4.189488e+01,-8.764117e+01,4.189576e+01,-8.764117e+01,9.973867e+00,1.500000e+01
75%,2025-09-20 09:42:11.876249856,2025-09-20 10:02:13.371749888,4.192586e+01,-8.762784e+01,4.192657e+01,-8.762858e+01,1.765890e+01,1.700000e+01
max,2025-12-31 23:53:24.274000,2025-12-31 23:57:07.715000,4.206485e+01,-8.752823e+01,4.206485e+01,-8.752823e+01,1.499638e+03,2.300000e+01
std,NaN,NaN,4.306454e-02,2.638825e-02,4.326038e-02,2.652941e-02,3.428007e+01,4.840922e+00

In [65]:
#final size of cleaned dataset
cyclistic.shape

(3661656, 17)

In [67]:
#save the cleaned dataset as a new CSV file to be used for analysis
cyclistic.to_csv('cyclistic_cleaned.csv', index = False)